bridge:
  ros2mqtt:            # array specifying which ROS topics to map to which MQTT topics
    - ros_topic: /Motors/FL        # ROS topic whose messages are transformed to MQTT messages
      mqtt_topic: Motors/FL       # MQTT topic on which the corresponding ROS messages are sent to the broker
      primitive: true        # [false] whether to publish as primitive message
    - ros_topic: /Motors/FR        # ROS topic whose messages are transformed to MQTT messages
      mqtt_topic: Motors/FR       # MQTT topic on which the corresponding ROS messages are sent to the broker
      primitive: true        # [false] whether to publish as primitive message
    - ros_topic: /Motors/BL        # ROS topic whose messages are transformed to MQTT messages
      mqtt_topic: Motors/BL       # MQTT topic on which the corresponding ROS messages are sent to the broker
      primitive: true        # [false] whether to publish as primitive message
    - ros_topic: /Motors/BR        # ROS topic whose messages are transformed to MQTT messages
      mqtt_topic: Motors/BR       # MQTT topic on which the corresponding ROS messages are sent to the broker
      primitive: true        # [false] whether to publish as primitive message
    - ros_topic: /Sprayer
      mqtt_topic: Sprayer
      primitive: true
      
  mqtt2ros:               # array specifying which MQTT topics to map to which ROS topics
    - mqtt_topic: RC/CH   # MQTT topic on which messages are received from the broker
      ros_topic: /RC/CH   # ROS topic on which corresponding MQTT messages are published
      primitive: true     # [false] whether to publish as primitive message (if coming from non-ROS MQTT client)